### ISSUE TITLE
HWND CreateWindow argument 3 cant convert cxonst_Elemt pointer to LPCWSTR

### ISSUE THREAD

**Issue by TheRealNOIG** [ahmetabdi/DeusExMachina#2]
![image](https://user-images.githubusercontent.com/11076398/82848430-03e99700-9eb9-11ea-90f3-dd65254adea0.png)
argument 3 cant convert cxonst_Elemt* to LPCWSTR

```C++
HWND hwnd = ::CreateWindow(wc.lpszClassName, random_string(12).c_str(), WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX, 100, 100, width, height, NULL, NULL, wc.hInstance, NULL);```

**Comment by ahmetabdi** [comment]
I think this is because it needs to be compiled as using multi byte strings

**Comment by TheRealNOIG** [comment]
I was unable to figure out how to change the build options but I just replaced it with a static long string.
I am still running into one more issue before I can build this project.
`if (name == proc_entry.szExeFile)`
This line is trying to compare a string to a wchar. Would this also be due to not having the build options work with unicode?
If so can you please point me to a resource that explains how I can change the build options on VS
